MTL       = ../mtl
CORE      = ../core
CHDRS     = $(wildcard *.hpp) $(wildcard $(MTL)/*.h)
EXEC      = minicsp
CFLAGS    = -fno-omit-frame-pointer -I../.. -Wall -ffloat-store -std=c++17
LFLAGS    = -lz

include ../mtl/template.mk
